### ISSUE TITLE
Consider adding task start time

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap-taskprov#62]
When deciding whether to opt in to a task, a party knows only when the task expires, not how long the task was in use. Imagine for example a client uploads a report to a task that expires in two years; then two years minus one month later, the Leader wants to aggregate it. Should the Helper oblige?

It sounds reasonable to include in the `TaskConfig` an indication of when the task began.

**Comment by junyechen1996** [comment]
While working on this: Can the aggregator figure out the start time when it receives the first report of a task ID? In the example:

> for example a client uploads a report to a task that expires in two years; then two years minus one month later, the Leader wants to aggregate it. Should the Helper oblige?

I think this is a valid case for helper to just process the request, since the task hasn't expired?

**Comment by cjpatton** [comment]
My suspiciion is that it will be helpful to stamp when the Task Author _intends_ for the task to begin. That way we can reject reports with timestamps begin prior to the start of the task.
