### ISSUE TITLE
More codepoints for DP mechansims?

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap-taskprov#83]
At the moment we've only allocated a byte for DP mechanism identifiers. For VDAFs we've allocated four bytes. It doesn't seem out of the question to me that we end up with more than 256 DP mechanisms.

**Comment by wangshan** [comment]
I doubt we'll have that many varieties of differential privacy. However, I think it's fnie to align with VDAF, extra 3 bytes should have no perf impact.
